name: publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Builder Number Generator
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.github_token }}
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'
    - name: Replace Versions
      run: |
        node ./build/replaceVersions.js ./queueing/package.json 2.0.$BUILD_NUMBER
        node ./build/replaceVersions.js ./http/package.json 2.0.$BUILD_NUMBER
        node ./build/replaceVersions.js ./http-service/package.json 2.0.$BUILD_NUMBER
        node ./build/replaceVersions.js ./mysql-data/package.json 2.0.$BUILD_NUMBER
        node ./build/replaceVersions.js ./configuration-client/package.json 2.0.$BUILD_NUMBER
        node ./build/replaceVersions.js ./logging-client/package.json 2.0.$BUILD_NUMBER
        node ./build/replaceVersions.js ./mongodb/package.json 2.0.$BUILD_NUMBER
    - name: Publish to npm
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        npm publish ./queueing --access public
        npm publish ./http --access public
        npm publish ./http-service --access public
        npm publish ./mysql-data --access public
        npm publish ./configuration-client --access public
        npm publish ./logging-client --access public
        npm publish ./mongodb --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PAT }}
