name: publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Builder Number Generator
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.github_token }}
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Replace Versions
      run: |
        node ./build/replaceVersions.js ./queueing/package.json 2.0.$BUILD_NUMBER
        node ./build/replaceVersions.js ./http/package.json 2.0.$BUILD_NUMBER
    - name: Login
      run: |
        node ./build/login.js ./.npmrc $NPM_EMAIL $NPM_PAT
    - name: Publish to npm
      # if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        npm publish ./queueing --access public --dry-run
        npm publish ./http --access public --dry-run
